[package]
name = "dom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dom-derive = { path = "../dom-derive"}

[build-dependencies]
syn = "1"
proc-macro2 = "1"